### ISSUE TITLE
Applet can't register with dbus

### ISSUE THREAD

**Issue by ghost** [equeim/snw-plugin#2]
The applet compiles withought errors .
Desktop : Mate 1.18
Versions tried : 0.9 and 0.10
Distro: Manjaro
When I run the applet I get this error : 
Could not register service
after eval $(dbus-launch) the error is not displayed anymore .
The applet renders on the panel but no notifiers .
Notes : Using ubuntu's patched libdbusmenu lib from AUR

**Comment by equeim** [comment]
Do you have notification area applet on the panel? Mate 1.18 has it own implementation of StatusNotifierWatcher which conflicts with snw-plugin.

**Comment by ghost** [comment]
Yes I have . But this is wath I did : 
1. Remove the notification area applet
2. Restart mate so dbus restarts asswell
3. Add the snw-plugin to the panel
But after that I get segfault:
zsh: segmentation fault (core dumped)  /usr/lib/mate-panel/snw-applet

**Comment by equeim** [comment]
That's strange. Core dump file should be located in /var/lib/systemd/coredump/. Could you send it to me?

**Comment by ghost** [comment]
Here it is .Github does not support sending lz4 compression files so here is a link to gdrive : 
https://drive.google.com/file/d/0B6PZ64HWssluNjF0THFZSXFhM2s/view?usp=sharing

**Comment by equeim** [comment]
Ouch, I forgot that you need to build package with debug symbols. Add `options=(debug !strip)` to PKGBUILD. Also architecture doesn't match.

If have experience with gdb, you can get stack trace by yourself. First, remove applet from panel. Then launch /usr/lib/mate-panel/snw-applet inside gdb, add applet to panel and reproduce a segfault.

Alternatively you can just send me core dump file with snw-applet binary.

**Comment by ghost** [comment]
Well I have never debuged until now :D 

Replecated it by removing notification area applet while snw-applet is running .

Hope this is wath you are looking for : 

```c++
(gdb) b 43
Breakpoint 1 at 0x80540a0: file mate-snw-applet.c, line 43.
(gdb) run
Starting program: /usr/lib/mate-panel/snw-applet 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0xb375fb40 (LWP 19241)]
[New Thread 0xb2f5eb40 (LWP 19242)]
[New Thread 0xb23ffb40 (LWP 19243)]
Could not register service

Thread 1 "snw-applet" received signal SIGSEGV, Segmentation fault.
0xb6f68a26 in __strlen_sse2_bsf () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0xb6f68a26 in __strlen_sse2_bsf () at /usr/lib/libc.so.6
#1  0x0804e675 in status_notifier_button_update_icon (self=0x82ca528)
    at statusnotifierbutton.c:651
#2  0x0804ec7a in status_notifier_button_proxy_got_all_properties (self=0x82ca528) at statusnotifierbutton.c:473
#3  0x0804ec7a in _status_notifier_button_proxy_got_all_properties_status_notifier_item_proxy_got_all_properties (_sender=0x819a960, self=0x82ca528)
    at statusnotifierbutton.c:254
#4  0xb720dc3b in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#5  0xb722001e in  () at /usr/lib/libgobject-2.0.so.0
#6  0xb7228bb6 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#7  0xb7229394 in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#8  0x08050e18 in __lambda7_ (object=0x80e0868, _result_=0x80e6390, self=0x819a960) at statusnotifieritem.c:1375
#9  0x08050e18 in ___lambda7__gasync_ready_callback (source_object=0x80e0868, res=0x80e6390, self=0x819a960) at statusnotifieritem.c:1402
#10 0xb72dfa20 in  () at /usr/lib/libgio-2.0.so.0
#11 0xb72e0142 in  () at /usr/lib/libgio-2.0.so.0
#12 0xb7315870 in  () at /usr/lib/libgio-2.0.so.0
#13 0xb72dfa20 in  () at /usr/lib/libgio-2.0.so.0
#14 0xb72dfa6b in  () at /usr/lib/libgio-2.0.so.0
#15 0xb711c18b in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#16 0xb711c579 in  () at /usr/lib/libglib-2.0.so.0
#17 0xb711c929 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#18 0xb797e33e in gtk_main () at /usr/lib/libgtk-3.so.0
---Type <return> to continue, or q <return> to quit---
#19 0xb70ccc82 in mate_panel_applet_factory_main ()
    at /usr/lib/libmate-panel-applet-4.so.1
#20 0x08054270 in _vala_main (args=<optimized out>, args_length1=<optimized out>) at mate-snw-applet.c:205
#21 0x0804b6bb in main (argc=1, argv=0xbffff834) at mate-snw-applet.c:213
```
